[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "spicewrapper"
authors = [{name = "Chiles", email = "pseudotexan@gmail.com"}]
dynamic = ["version", "description"]
